config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
    get    :add_item
    get    :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, :categories, except: [:edit, :update, :show]
  end

  get '/register' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :require_login

  def add_item
    byebug
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 0 }
    item["quantity"] += 1
    cart[product_id] = item
    update_cart cart

    redirect_back(fallback_location: root_path)
  end

  def remove_item
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 1 }
    item["quantity"] -= 1
    cart[product_id] = item
    cart.delete(product_id) if item["quantity"] < 1
    update_cart cart

    redirect_back(fallback_location: root_path)
  end

end

app/views/carts/_item.html.erb
<% quantity = details['quantity'].to_i %>

<% if product = Product.find_by(id: product_id) %>
  <% item_total = product.price * quantity %>
  <% @cart_total += item_total %>

  <tr>
    <td>
      <%= image_tag product.image.url,style: 'max-width: 200px; max-height: 200px;' %>
      <%#= image_tag "http://localhost:3000/assets/1star.png" %>
    </td>
    <td>
      <h4><%= product.name %></h4>
      <br>
      <p><%= product.description %></p>
    </td>
    <td>
      $<%= product.price %>
    </td>
    <td>
      <%= link_to remove_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-danger', method: :delete do %>
        -
      <% end %>
      <%= quantity %>
      <%= link_to add_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-success', method: :put do %>
        +
      <% end %>
    </td>
    <td>
      $<%= item_total %>
    </td>
  </tr>
<% end %>

app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>


  <% if cart.blank? %>

  <div class="alert alert-warning" role="alert">
   Your cart is empty, Please give a look at our products and buy something!
  </div>

   <% else %>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_total = 0 %>
        <% cart.each do |product_id, details| %>
          <%= render 'item', product_id: product_id, details: details %>
          <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
            $<%= @cart_total %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= @cart_total * 100 %>"
          data-name="Jungle"
          data-description="<%= current_user.firstname %> <%= current_user.lastname %>'s Jungle Order"
          data-locale="auto"
          data-email="<%= current_user.email %>"
          data-currency="cad">
        </script>
      <% end %>
    </div>
  </div>
  <% end %>

  <br>
  <br>

</section>