config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
    get    :add_item
    get    :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, :categories, except: [:edit, :update, :show]
  end

  get '/register' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category
  has_many :reviews, -> { order(created_at: :desc) }

  validates_presence_of :name, :price, :quantity, :category


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = "Product created!"
      redirect_to [:admin, :products]
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    flash[:danger] = "Product has been deleted."
    redirect_to [:admin, :products]
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/views/products/_product.html.erb
<article class="product">
  <header>
    <%= link_to product do %>
    <%= image_tag product.image.url, alt: product.name %>
    <h4><%= product.name %></h4>
    <% end %>
  </header>
  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <% if product.quantity > 0 %>
      <%= link_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary', method: :put do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
      <% end %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
    Details &raquo;
    <% end %>
  </footer>

  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>
  <% if product.quantity == 0 %>
  <%= out_of_stock %>
  <% end %>
</article>

app/views/products/index.html.erb
<section class="products-index">

  <header class="page-header">
    <h1>Products</h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd>$ <%= @product.price %></dd>
        </dl>
      </div>
      <div class="col-sm-8">
        <br>
        <dl class="dl-horizontal">
          <% if current_user %>
            <%= form_for(Review.new, url: product_reviews_path(@product, @review)) do |f| %>
            <dt>Add a Review</dt>
            <dd><%= f.text_area :description, class: "form-control" %></dd>
            <br>
            <dt>Rating</dt>
            <dd>
              <%= f.select :rating,
                  options_for_select(
                  [['Excellent', 5],
                  ['Good', 4],
                  ['Average', 3],
                  ['Could be improved', 2],
                  ['Poor', 1]]),
                  class: "form-control" %>
            </dd>
            <br>
            <dd><%= f.submit "Submit Review", class: "btn btn-primary" %></dd>
            <% end %>
          <% end %>
          <br>
          <% @product.reviews.each do |i| %>
          <dt><%= show_stars i.rating %></dt>
          <dd>
            <%= i.description %>
            <br>
            Review submitted <%= i.created_at.strftime("%d %B %Y") %>
            <br>
            <% if i.user == current_user %>
              <%= link_to "DELETE REVIEW",
                  product_review_path(@product, i),
                  :method => :delete,
                  class: "btn btn-danger"
                  %>
            <% end %>
          </dd>
          <br>
          <% end %>
        </dl>
      </div>
    </div>

  </article>

</section>