config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
    get    :add_item
    get    :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, :categories, except: [:edit, :update, :show]
  end

  get '/register' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
  <%= value %>
</div>
<% end %>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Jungle</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', :root %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li>
          <%= link_to cart_path do %>
            <%= fa_icon "shopping-cart" %> My Cart (<%= cart.size %>)
          <% end %>
        </li>
        <li><a href="#">Signed in as <%= current_user.firstname %></a></li>
        <li><%= link_to "Logout", '/logout' %></li>
          <% else %>
          <li><%= link_to 'Login', '/login' %></li>
          <li><%= link_to 'Register', '/register' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jungle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
  <%= csrf_meta_tags %>
</head>
<body>




  <%= render 'layouts/top_nav' %>

  <main class="container">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </main>

  <%= yield :end_of_body %>
  
</body>
</html>